name: mvvm_temp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.0
  dio: ^5.2.1+1
  firebase_analytics: ^10.5.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_remote_config: ^4.2.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  get_it: ^7.6.0
  http_parser: ^4.0.2
  intl: any
  local_auth: ^2.1.6
  logging: ^1.2.0
  lottie: ^2.3.2
  mime: ^1.0.4
  mixpanel_flutter: ^2.1.1
  package_info_plus: ^4.2.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
